apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-weather
  labels:
    type: local
    app: db
spec:
  storageClassName: manual
  capacity: 
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/kube-data/weather"