apiVersion: v1
kind: ConfigMap
metadata:
  name: balancer-config
data:
  nginx.conf: |
    upstream backend-dp {
        server backend-service:80;
    }

    upstream frontend-dp {
        server frontend-service:80;
    }

    server {
      listen 80;

      access_log /dev/stdout;
      error_log /dev/stdout info;

      gzip on;
      gzip_vary on;
      gzip_proxied any;
      gzip_min_length  1000;
      gzip_buffers 16 8k;
      gzip_http_version 1.0;
      gzip_comp_level 7;
      gzip_types
        text/plain
        text/css
        text/js
        text/xml
        text/javascript
        application/javascript
        application/json
        application/xml
        application/rss+xml
        image/svg+xml;

      location /api/ {
        proxy_pass http://backend-dp/;
        proxy_redirect     off;
      }

      location / {
        proxy_pass http://frontend-dp/;
        proxy_redirect     off;
      }

      error_page   500 502 503 504  /50x.html;

      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }