apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: weather-balancer

spec:
  replicas: 1
  selector:
    matchLabels:    
      app: balancer

  template:
    metadata:
      name: balancer
      labels:
        app: balancer
    spec:
      containers:
      - name: balancer
        image: nginx:1.29-bookworm
        ports:
        - containerPort: 80
        volumeMounts:
            - name: nginx-config
              mountPath: "/etc/nginx/conf.d"
              
      volumes:
        - name: nginx-config
          configMap:
            name: balancer-config
  