apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-weather
  labels:
    app: db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi