apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: weather-database

spec:
  replicas: 1
  selector:
    matchLabels:    
      app: postgres

  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17-bullseye

        ports:
        - containerPort: 5432

        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql

        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgressecret
              key: POSTGRES_PASSWORD

        - name: PGDATA
          value: /var/lib/postgresql/data/weather/

      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: postgres-weather