apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
spec:
  template:
    spec:
      containers:
        - name: db-init
          image: postgres:17-bullseye
          command: ["psql"]
          args:
            ["-h", "postgres-service", "-U", "postgres", "-d", "postgres", "-f", "/init/create_db.sql"]
          env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: postgressecret
                key: POSTGRES_PASSWORD
          volumeMounts:
            - name: init-script
              mountPath: /init
      restartPolicy: Never
      volumes:
        - name: init-script
          configMap:
            name: create-db-script